#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""v1.4.0 — +30 عبارة اطمئنان جديدة ×6 لغات (بمفردات علم النفس)
   تُضاف إلى shared/uplift-quotes.json — البذر التزايدي في /api/quotes
   يزرعها تلقائياً في القواعد القديمة (مطابقة بالنص العربي، بلا تكرار)."""

import json, io

NEW = [
 {"cat":"wisdom","au":"","ar":"ما تمرّ به ليس سهلاً… ولا تحتاج أن تحمل همّك وحدك","fr":"Ce que vous traversez n'est pas facile… et vous n'avez pas à porter ce fardeau seul","en":"What you're going through isn't easy… and you don't have to carry it alone","tr":"Yaşadığın kolay değil… ve bu yükü tek başına taşmak zorunda değilsin","ru":"То, что вы переживаете, непросто… и не нужно нести это в одиночку","zh":"你正在经历的不容易……你不必独自承担"},
 {"cat":"wisdom","au":"","ar":"طلب المساعدة قوة، ليس ضعفاً — هذا أول درس في علم النفس","fr":"Demander de l'aide est une force, pas une faiblesse — c'est la première leçon de psychologie","en":"Asking for help is strength, not weakness — the first lesson of psychology","tr":"Yardım istemek güçlüktür, zayıflık değil — psikolojinin ilk dersi","ru":"Просить о помощи — сила, а не слабость — первый урок психологии","zh":"求助是力量而非软弱——这是心理学的第一课"},
 {"cat":"wisdom","au":"","ar":"مشاعرك صالحة ولو كانت مؤلمة — الاعتراف بها أول خطوة في التعافي","fr":"Vos émotions sont valides, même douloureuses — les reconnaître est le premier pas du rétablissement","en":"Your feelings are valid even when painful — acknowledging them is the first step of recovery","tr":"Duygularınız geçerli, acıverici olsalar bile — onları kabul etmek iyileşmenin ilk adımıdır","ru":"Ваши чувства оправданы, даже если они болезненны — признать их — первый шаг восстановления","zh":"你的情绪都是正当的，即使痛苦——承认它们是康复的第一步"},
 {"cat":"wisdom","au":"","ar":"الشفاء ليس خطاً مستقيماً — الانتكاسات جزء طبيعي من رحلة التعافي","fr":"La guérison n'est pas une ligne droite — les rechutes font partie du parcours","en":"Healing isn't a straight line — setbacks are a natural part of the recovery journey","tr":"İyileşme düz bir çizgi değildir — geri kaymalar iyileşme yolculuğunun doğal parçasıdır","ru":"Исцеление — не прямая линия — откаты — естественная часть пути восстановления","zh":"康复不是一条直线——反复是康复旅程的自然部分"},
 {"cat":"wisdom","au":"","ar":"أفكارك ليست حقائق — تعلّم أن تفصل بين ما يخبرك به عقلك وما هو كائن فعلاً","fr":"Vos pensées ne sont pas des faits — apprenez à distinguer ce que votre esprit raconte de la réalité","en":"Your thoughts are not facts — learn to separate what your mind tells you from what is real","tr":"Düşünceleriniz gerçek değildir — zihninizin söylediklerini gerçekten ayırmayı öğrenin","ru":"Ваши мысли — не факты — учитесь отделять то, что говорит разум, от реальности","zh":"你的想法并非事实——学会区分大脑告诉你的和真实存在的"},
 {"cat":"wisdom","au":"","ar":"تنفّس بعمق — استجابة الاسترخاء أقوى مما تظن، وجسدك يعرف الطريق","fr":"Respirez profondément — la réponse de relaxation est plus puissante qu'on ne le croit","en":"Breathe deeply — the relaxation response is more powerful than you think","tr":"Derence nefes alın — gevşeme tepkisi düşündüğünüzden güçlüdür","ru":"Дышите глубоко — реакция расслабления сильнее, чем кажется","zh":"深呼吸——放松反应比你想象的更强大"},
 {"cat":"social","au":"","ar":"الحديث عن نفسك ليس تذمّراً — إنه علاج نفساني حقيقي يُسمّى التفريغ العاطفي","fr":"Parler de vous n'est pas se plaindre — c'est une vraie thérapie appelée catharsis émotionnelle","en":"Talking about yourself isn't complaining — it's real therapy called emotional catharsis","tr":"Kendinizden konuşmak şikâyet değil — duygusal arınma denen gerçek bir terapidir","ru":"Говорить о себе — не нытьё — это настоящая терапия, называемая эмоциональной разрядкой","zh":"谈论自己不是抱怨——这是一种被称为情绪宣泄的真实疗法"},
 {"cat":"wisdom","au":"","ar":"لست حالة تشخيص — أنت إنسان كامل يستحق أن يُسمَع دون حكم","fr":"Vous n'êtes pas un diagnostic — vous êtes une personne entière qui mérite d'être écoutée sans jugement","en":"You are not a diagnosis — you are a whole person deserving to be heard without judgment","tr":"Bir teşhis değilsiniz — yargısız dinlenmeyi hak eden bütün bir insansınız","ru":"Вы не диагноз — вы целый человек, заслуживающий быть услышанным без осуждения","zh":"你不是一个诊断标签——你是一个完整的、值得被不评判倾听的人"},
 {"cat":"wisdom","au":"","ar":"القلق رسول لا سيد — يستحق أن تسمعه، لا أن تتركه يقود حياتك","fr":"L'anxiété est un messager, pas un maître — elle mérite d'être entendue, pas de vous gouverner","en":"Anxiety is a messenger, not a master — it deserves to be heard, not to run your life","tr":"Kaygı bir habercidir, efendi değil — dinlenmeyi hak eder, hayatınızı yönetmez","ru":"Тревога — вестник, а не хозяин — её стоит выслушать, а не позволять ей управлять жизнью","zh":"焦虑是信使而非主人——值得被听见，但不该主导你的生活"},
 {"cat":"social","au":"","ar":"مَن يستمع إليك بصدق يمنحك أكثر من نصيحة — يمنحك مساحة أمان نفسية","fr":"Celui qui vous écoute sincèrement vous donne plus qu'un conseil — il vous offre un espace de sécurité psychologique","en":"Whoever truly listens gives you more than advice — they give you a psychologically safe space","tr":"Sizi gerçekten dinleyen sadece tavsiye vermez — psikolojik olarak güvenli bir alan sunar","ru":"Тот, кто по-настоящему слушает, даёт больше совета — он даёт пространство психологической безопасности","zh":"真诚倾听你的人给你的不只是建议——而是一个心理安全的空间"},
 {"cat":"wisdom","au":"","ar":"النوم ليس رفاهية — إنه حجر الأساس في صحتك النفسية","fr":"Le sommeil n'est pas un luxe — c'est la pierre angulaire de votre santé mentale","en":"Sleep isn't a luxury — it's the cornerstone of your mental health","tr":"Uyku bir lüks değildir — ruh sağlığınızın köşe taşıdır","ru":"Сон — не роскошь — это краеугольный камень психического здоровья","zh":"睡眠不是奢侈——它是心理健康的基石"},
 {"cat":"wisdom","au":"","ar":"كتابة مشاعرك عشر دقائق يومياً تُخفّف العبء الذي يحمله عقلك","fr":"Écrire vos émotions dix minutes par jour allège le fardeau de votre esprit","en":"Writing your feelings ten minutes a day lightens the load on your mind","tr":"Duygularınızı günde on dakika yazmak zihninizin yükünü hafifletir","ru":"Записывание чувств по десять минут в день облегчает груз разума","zh":"每天花十分钟写下你的感受，可以减轻大脑的负担"},
 {"cat":"social","au":"","ar":"المقارنة سرقة للفرح — رحلتك النفسية تقاس بتقدّمك أنت لا بشخص آخر","fr":"La comparaison vole la joie — votre parcours psychologique se mesure à vos progrès, pas à ceux d'autrui","en":"Comparison steals joy — your psychological journey is measured by your progress, not by others","tr":"Karşılaştırma neşeyi çalar — psikolojik yolculuğunuz kendi ilerlemenizle ölçülür","ru":"Сравнение крадёт радость — ваш психологический путь измеряется вашим прогрессом","zh":"比较会偷走快乐——你的心理旅程由你自己的进步来衡量"},
 {"cat":"wisdom","au":"","ar":"الحدود الصحية ليست جفاء — إنها احترام لنفسك ولعلاقاتك","fr":"Les limites saines ne sont pas de la froideur — c'est du respect pour vous et vos relations","en":"Healthy boundaries aren't coldness — they're respect for yourself and your relationships","tr":"Sağlıklı sınırlar soğukkanlılık değildir — kendinize ve ilişkilerinize saygıdır","ru":"Здоровые границы — не холодность — это уважение к себе и отношениям","zh":"健康的界限不是冷漠——而是对自己和关系的尊重"},
 {"cat":"wisdom","au":"","ar":"جسدك يسجّل ما لا تقوله كلمات — استرح حين يثقل صدرك بلا سبب واضح","fr":"Votre corps enregistre ce que les mots ne disent pas — reposez-vous quand votre poitrine s'alourdit sans raison","en":"Your body records what words don't say — rest when your chest feels heavy for no clear reason","tr":"Bedeniniz kelimelerin söylemediğini kaydeder — göğsünüz sebepsiz ağırlaştığında dinlenin","ru":"Тело записывает то, чего не говорят слова — отдыхайте, когда тяжело на душе без причины","zh":"身体记录着言语未说出的——当莫名感到沉重时，请休息"},
 {"cat":"social","au":"","ar":"وجود شخص يصدّقك وحده كفيل بتخفيف نصف الثقل","fr":"Avoir quelqu'un qui vous croit suffit à alléger la moitié du poids","en":"Having one person believe you is enough to lighten half the weight","tr":"Size inanan bir kişinin olması yükün yarısını hafifletmeye yeter","ru":"Достаточно одного человека, который вам верит, чтобы облегчить половину груза","zh":"有一个相信你的人，就足以减轻一半的重量"},
 {"cat":"wisdom","au":"","ar":"الغضب غالباً حزن يرتدي درعاً — اسأل نفسك: ما الذي جرحني حقاً؟","fr":"La colère est souvent une tristesse en armure — demandez-vous : qu'est-ce qui m'a vraiment blessé ?","en":"Anger is often grief wearing armor — ask yourself: what really hurt me?","tr":"Öfke çoğu zaman zırh giymiş bir üzüntüdür — sorun: beni gerçekten ne incitti?","ru":"Гнев — часто печаль в доспехах — спросите себя: что меня по-настоящему ранило?","zh":"愤怒常常是披着盔甲的悲伤——问问自己：真正伤害我的是什么？"},
 {"cat":"wisdom","au":"","ar":"الاعتناء بنفسك ليس أنانية — لا يمكنك أن تسقي غيرك من وعاء فارغ","fr":"Prendre soin de vous n'est pas de l'égoïsme — on ne peut pas verser d'un vase vide","en":"Self-care isn't selfishness — you can't pour from an empty cup","tr":"Kendinize bakmak bencillik değildir — boş bardaktan kimseye su dökülemez","ru":"Забота о себе — не эгоизм — из пустой чаши не нальёшь","zh":"照顾自己不是自私——空杯无法倒水给别人"},
 {"cat":"social","au":"","ar":"جلسة استشارة واحدة قد تكون بداية تحوّل عظيم — الخطوة الأولى نصف الطريق","fr":"Une seule séance de consultation peut être le début d'un grand changement — le premier pas est la moitié du chemin","en":"A single consultation session can be the start of a great transformation — the first step is half the journey","tr":"Tek bir danışmanlık seansı büyük bir dönüşümün başlangıcı olabilir — ilk adım yolun yarısıdır","ru":"Одна консультация может стать началом большого переворота — первый шаг — половина пути","zh":"一次咨询就可能成为巨大转变的开端——第一步就是旅程的一半"},
 {"cat":"wisdom","au":"","ar":"الذكريات المؤلمة تُعالج ولا تُمحى — ووقوفك اليوم دليل على قوتك","fr":"Les souvenirs douloureux se traitent, ne s'effacent pas — votre tenue aujourd'hui prouve votre force","en":"Painful memories are processed, not erased — your standing today proves your strength","tr":"Acıverici anılar işlenir, silinmez — bugün ayakta olmanız gücünüzün kanıtıdır","ru":"Болезненные воспоминания прорабатываются, а не стираются — то, что вы стоите, доказывает вашу силу","zh":"痛苦的记忆是被疗愈而非被抹去——你今天依然站立就是力量的证明"},
 {"cat":"wisdom","au":"","ar":"التركيز على اللحظة الحاضرة أقوى أدوات الهدوء — اسمه اليقظة الذهنية","fr":"Se concentrer sur le moment présent est l'outil d'apaisement le plus puissant — c'est la pleine conscience","en":"Focusing on the present moment is the most powerful calming tool — it's called mindfulness","tr":"Şimdiki ana odaklanmak en güçlü sakinleşme aracıdır — buna farkındalık denir","ru":"Фокус на настоящем моменте — сильнейший инструмент успокоения — это осознанность","zh":"专注于当下是最有力的平静工具——它叫做正念"},
 {"cat":"social","au":"","ar":"دعم عزيزك لا يحتاج كلاماً كبيراً — حضوريك الصامت علاج بحد ذاته","fr":"Soutenir un proche n'exige pas de grands discours — votre présence silencieuse est déjà thérapeutique","en":"Supporting a loved one doesn't need big words — your silent presence is itself healing","tr":"Sevdiğiniz birine destek büyük sözler gerektirmez — sessiz varlığınız bile şifadır","ru":"Поддержать близкого не нужны большие слова — ваше молчаливое присутствие уже целительно","zh":"支持所爱之人不需要豪言壮语——你安静的陪伴本身就是疗愈"},
 {"cat":"wisdom","au":"","ar":"التعب العاطفي حقيقي كتعب الجسد — منحه اعترافاً هو بداية تعافيه","fr":"La fatigue émotionnelle est aussi réelle que physique — la reconnaître est le début de son apaisement","en":"Emotional exhaustion is as real as physical — acknowledging it is the beginning of relief","tr":"Duygusal yorgunluk fiziksel yorgunluk kadar gerçektir — onu kabul etmek rahatlamanın başlangıcıdır","ru":"Эмоциональное истощение так же реально, как физическое — признать его — начало облегчения","zh":"情绪疲惫和身体疲惫一样真实——承认它是缓解的开始"},
 {"cat":"wisdom","au":"","ar":"لا تقارن داخلك بهدوء الآخرين — وراء كل هدوء قصة صراع لم تسمعها","fr":"Ne comparez pas votre intérieur au calme des autres — derrière chaque calme se cache une lutte que vous n'avez pas entendue","en":"Don't compare your inside to others' calm — behind every calm is a struggle you haven't heard","tr":"İç dünyanızı başkalarının sakinliğiyle karşılaştırmayın — her sakinliğin arkasında duymadığınız bir mücadele var","ru":"Не сравнивайте свой внутренний мир с чужим спокойствием — за каждым спокойствием борьба, которую вы не слышали","zh":"不要拿你的内心与别人的平静比较——每份平静背后都有你未听闻的挣扎"},
 {"cat":"wisdom","au":"","ar":"الخوف قبل التغيير طبيعي — حتى التحولات الجميلة تُراعق قلوبنا قبل أن تُطمئنّها","fr":"La peur avant le changement est normale — même les belles transformations font d'abord trembler","en":"Fear before change is natural — even beautiful transformations unsettle us at first","tr":"Değişim öncesi korku doğaldır — güzel dönüşümler bile önce kalbi tedirgin eder","ru":"Страх перед переменами естественен — даже прекрасные перемены сначала тревожат","zh":"改变前的恐惧很正常——即使美好的转变也会先让心不安"},
 {"cat":"social","au":"","ar":"اسأل من تحب: «كيف أنت حقاً؟» — السؤال الصادق يفتح أبواباً مقفلة طويلاً","fr":"Demandez à ceux que vous aimez : « Comment allez-vous vraiment ? » — une question sincère ouvre des portes longtemps fermées","en":"Ask those you love: 'How are you really?' — a sincere question opens long-locked doors","tr":"Sevdiklerinize sorun: «Gerçekten nasılsınız?» — samimi bir soru uzun süredir kapalı kapıları açar","ru":"Спросите близких: «Как вы на самом деле?» — искренний вопрос открывает давно закрытые двери","zh":"问问你所爱的人：「你真的还好吗？」——真诚的提问能打开尘封已久的门"},
 {"cat":"wisdom","au":"","ar":"التقدّم الصغير لا يزال تقدّماً — احتفِ بكل خطوة ولو بدت بسيطة","fr":"Un petit progrès reste un progrès — célébrez chaque pas, même s'il paraît simple","en":"Small progress is still progress — celebrate every step, however simple it seems","tr":"Küçük ilerleme yine ilerlemedir — her adımı kutlayın, ne kadar basit görünse de","ru":"Малый прогресс — всё же прогресс — празднуйте каждый шаг, каким бы простым он ни был","zh":"小进步也是进步——庆祝每一步，无论多么简单"},
 {"cat":"wisdom","au":"","ar":"صوتك الداخلي يستحق نفس اللطف الذي تمنحه لمن تحب","fr":"Votre voix intérieure mérite la même douceur que celle que vous offrez à ceux que vous aimez","en":"Your inner voice deserves the same kindness you give to those you love","tr":"İç sesiniz sevdiklerinize gösterdiğiniz şefkati hak eder","ru":"Ваш внутренний голос заслуживает той же нежности, что вы дарите близким","zh":"你内心的声音值得获得你给予所爱之人的同样温柔"},
 {"cat":"social","au":"","ar":"الثقة بالمختص تُبنى تدريجياً — لا تتجاهل الانطباع الأول، فالعلاقة العلاجية شفاء بحد ذاتها","fr":"La confiance en un professionnel se construit — l'alliance thérapeutique est déjà un soin","en":"Trust in a specialist builds gradually — the therapeutic alliance is itself healing","tr":"Bir uzmana güven zamanla kurulur — terapötik ittifakın kendisi bir şifadır","ru":"Доверие к специалисту строится постепенно — терапевтический альянс сам по себе исцеляет","zh":"对咨询师的信任是逐步建立的——治疗联盟本身就是疗愈"},
 {"cat":"wisdom","au":"","ar":"ما تشعر به اليوم لن يبقى كما هو — المشاعر أمواج، حتى الأشد عظوراً يمرّ","fr":"Ce que vous ressentez aujourd'hui ne restera pas — les émotions sont des vagues, même les plus fortes passent","en":"What you feel today won't stay — emotions are waves, even the strongest ones pass","tr":"Bugün hissettikleriniz böyle kalmayacak — duygular dalgadır, en güçlüsü bile geçer","ru":"То, что вы чувствуете сегодня, не останется навсегда — эмоции как волны, даже самые сильные проходят","zh":"今天的感受不会永远持续——情绪如浪潮，再强烈的也会过去"},
]

path = "shared/uplift-quotes.json"
data = json.load(io.open(path, encoding="utf-8"))
have = {q["ar"].strip() for q in data}
added = 0
for q in NEW:
    if q["ar"].strip() not in have:
        data.append(q)
        added += 1
io.open(path, "w", encoding="utf-8").write(json.dumps(data, ensure_ascii=False, indent=1))
print(f"added {added} quotes — total {len(data)}")
